# Generated by Django 4.2.11 on 2024-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Starters', 'Starters'), ('Main Dishes', 'Main Dishes'), ('Desserts', 'Desserts'), ("Today's Pick", "Today's Pick")], max_length=20)),
                ('photo', models.URLField()),
            ],
        ),
    ]
